task:
  name: Flake8
  container:
    image: $STEMNS_IMAGE
    cpu: 1
    memory: 1G
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo Flake8 && echo $STEMNS_IMAGE
    populate_script: mkdir -p ~/.cache/pip
  install_script:
    - pip install flake8
  flake8_script:
    - flake8 . --count --select=E,F,W,C90 --show-source --statistics
  env:
    STEMNS_IMAGE: python:3.7

task:
  name: "Missing torrc $CI_CONTROL_PORT"
  container:
    image: fedora:latest
    cpu: 1
    memory: 1G
  install_script:
    - dnf install -y tor python3-stem
  matrix:
    - env:
        CI_CONTROL_PORT: "const"
      port_script:
        - echo "ControlPort 9051" >> /etc/tor/torrc
        - cd ./config
        - ln -s -T port_const_system.py.example port_const_system.py
    - env:
        CI_CONTROL_PORT: "auto"
      port_script:
        - echo "ControlPort auto" >> /etc/tor/torrc
        - echo "ControlPortWriteToFile /var/lib/tor/controlport" >> /etc/tor/torrc
        - cd ./config
        - ln -s -T port_auto.py.example port_auto.py
  tor_background_script:
    - echo "CookieAuthentication 1" >> /etc/tor/torrc
    - tor --runasdaemon 0 --defaults-torrc /usr/share/tor/defaults-torrc -f /etc/tor/torrc
  stemns_script:
    - if ./stemns.py &> out.txt
    - then
    - exit 1
    - fi
    - cat out.txt
    - grep "torrc is unsafe for name lookups" out.txt
